FROM vital987/vubuntu:latest

ENV     DEBIAN_FRONTEND=noninteractive \
  #VNC Server Password
	VNC_PASS="samplepass" \
#VNC Server Title(w/o spaces)
	VNC_TITLE="Vubuntu" \
#VNC Resolution(720p is preferable)
	VNC_RESOLUTION="1800x960" \
#NoVNC Port
	NOVNC_PORT=5900 \
#PORT
        PORT=80 \
#Disable Shared Memory for Brave
	BRAVE_USE_SHM=0 \
#Locale
	LANG=zh_CN.UTF-8 \
	LANGUAGE=zh_CN.UTF-8 \
	LC_ALL=zh_CN.UTF-8 \
	TZ="Asia/Shanghai"
	
COPY    new /root/

ENTRYPOINT  ["/root/new/new.sh"]
